ht_werke/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^administracija/', include('projects.urls')),
    url(r'^', include('projects.urls')), # posle je moguce ubaciti sajt na ovoj adresi, druga aplikacija
]
admin.site.site_header = "HT WERKE admin"

projects/urls.py
from django.conf.urls import url
from . import views


app_name = 'projects'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^radnici/$', views.ljudi, name='ljudi'),
    url(r'^vozila/$', views.vozila, name='vozila'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^novi_projekat/$', views.create_project, name='project-add'),
    url(r'^mesecni_pregled_radnika/(?P<mesec>[0-9]+)/(?P<godina>[0-9]+)/(?P<posao_id>[a-zA-Z0-9_.-]+)$', views.mesecni_izvod_radnika, name='monthview-workers'),  # samo string (?P<posao>[\w\-]+)
    url(r'^mesecni_pregled_poslova/(?P<mesec>[0-9]+)/(?P<godina>[0-9]+)$', views.mesecni_izvod_poslova, name='monthview-projects'),
    url(r'^posao/(?P<project_id>[0-9]+)/$', views.detail, name='posao'),
    url(r'^radnik/(?P<radnik_id>[0-9]+)/$', views.radnik_detail, name='radnik-detail'),
    url(r'^vozilo/(?P<vozilo_id>[0-9]+)/$', views.vozilo_detail, name='vozilo-detail'),
    url(r'^komentar/(?P<komentar_id>[0-9]+)/$', views.komentar_detail, name='komentar-detail'),
    url(r'^azuriranje_posla/(?P<project_id>[0-9]+)/$', views.posao_update, name='posao-update'),
    url(r'^azuriranje_radnika/(?P<radnik_id>[0-9]+)/$', views.radnik_update, name='radnik-update'),
    url(r'^azuriranje_dana/(?P<dan_id>[0-9]+)/(?P<posao_id>[a-zA-Z0-9_.-]+)$', views.dan_update, name='dan-update'),
    url(r'^azuriranje_akontacije/(?P<mesec>[0-9]+)/(?P<godina>[0-9]+)/(?P<posao_id>[a-zA-Z0-9_.-]+)/(?P<akontacija_id>[0-9]+)$', views.akontacija_update, name='akontacija-update'),
    url(r'^azuriranje_vozila/(?P<vozilo_id>[0-9]+)/$', views.vozilo_update, name='vozilo-update'),
    url(r'^izmena_komentara/(?P<komentar_id>[0-9]+)/$', views.komentar_update, name='komentar-update'),
    url(r'^novi_prihod/(?P<project_id>[0-9]+)/$', views.create_prihod, name='prihod-add'),
    url(r'^novi_rashod/(?P<project_id>[0-9]+)/$', views.create_rashod, name='rashod-add'),
    url(r'^novi_kvadrati/(?P<project_id>[0-9]+)/$', views.create_kvadrat, name='kvadrat-add'),
    url(r'^novi_komentar/(?P<project_id>[0-9]+)/$', views.create_komentar, name='komentar-add'),
    url(r'^novo_zanimanje/$', views.create_zanimanje, name='zanimanje-add'),
    url(r'^novi_radnik/$', views.create_radnik, name='radnik-add'),
    url(r'^novo_vozilo/$', views.create_vozilo, name='vozilo-add'),
    url(r'^posao/(?P<project_id>[0-9]+)/obrisi_prihod/(?P<prihod_id>[0-9]+)/$', views.prihod_delete, name='prihod-delete'),
    url(r'^(?P<project_id>[0-9]+)/obrisi_rashod/(?P<rashod_id>[0-9]+)/$', views.rashod_delete, name='rashod-delete'),
    url(r'^(?P<project_id>[0-9]+)/obrisi_komentar/(?P<komentar_id>[0-9]+)/$', views.komentar_delete, name='komentar-delete'),
    url(r'^obrisi_posao/(?P<posao_id>[0-9]+)/$', views.posao_delete, name='posao-delete'),
    url(r'^biranje_meseca/$', views.biranje_meseca, name='biranje_meseca'),
    url(r'^biranje_meseca_finansije/$', views.biranje_meseca_za_finansije, name='biranje_meseca_finansije'),
    url(r'^dodaj_dane/(?P<mesec>[0-9]+)/(?P<godina>[0-9]+)/(?P<posao_id>[a-zA-Z0-9_.-]+)$', views.dodaj_dane, name='dodaj_dane'),
    url(r'^pdf/(?P<posao_id>[0-9]+)$', views.pdf_posao, name='pdf_posao')
]

projects/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models


class Poslovi(models.Model):
    ime = models.CharField(max_length=30)
    opis = models.CharField(max_length=100, blank=True)
    dogovoreni_radni_sati = models.FloatField(default=0.0)
    dogovoreno_po_kvadratu = models.FloatField(default=0.0)
    pocetak_radova = models.DateField()
    kraj_radova = models.DateField(null=True, blank=True)

    def __unicode__(self):
        return self.ime

    class Meta:
        verbose_name_plural = "Poslovi"


class Zanimanja(models.Model):
    zanimanje = models.CharField(max_length=30)

    def __unicode__(self):
        return self.zanimanje

    class Meta:
        verbose_name_plural = "Zanimanja"


class Radnik(models.Model):
    ime = models.CharField(max_length=50)
    oib = models.IntegerField()
    broj_telefona = models.CharField(max_length=30, blank=True)
    broj_odela = models.IntegerField(default=None, null=True, blank=True)
    broj_cipela = models.IntegerField(default=None, null=True, blank=True)
    poceo_raditi = models.DateField()
    ugovor_vazi_do = models.DateField()
    satnica = models.FloatField(max_length=10)
    zaduzena_oprema = models.CharField(max_length=100, blank=True)
    dostupan = models.BooleanField(default=True)
    posao = models.ForeignKey(Poslovi, null=True, blank=True, on_delete=models.SET_NULL)
    u_radnom_odnosu = models.BooleanField(default=True)
    zanimanja = models.ManyToManyField(Zanimanja)
    dana_do_isteka_ugovora = models.IntegerField(default=None, null=True, blank=True)
    komentar = models.CharField(max_length=500, blank=True)

    def __unicode__(self):
        return self.ime

    class Meta:
        verbose_name_plural = "Radnici"


class Vozilo(models.Model):
    marka = models.CharField(max_length=30)
    predjeni_kilometri = models.IntegerField(default=None, null=True, blank=True)
    registracija_istice = models.DateField()
    sledeci_servis = models.DateField(null=True, blank=True)
    potrosnja_goriva = models.FloatField(max_length=10, default=0.0)
    opis = models.CharField(max_length=100, blank=True)
    trenutno_duzi = models.ForeignKey(Radnik, null=True, blank=True)

    def __unicode__(self):
        return self.marka

    class Meta:
        verbose_name_plural = "Vozila"


class Dan(models.Model):
    datum = models.DateField()
    radnik = models.ForeignKey(Radnik, on_delete=models.CASCADE)
    posao = models.ForeignKey(Poslovi, null=True, blank=True)
    radio_sati = models.FloatField(max_length=10, default=0.0)
    ishrana = models.FloatField(max_length=10, default=0.0)
    bolovanje = models.BooleanField(default=False)
    dozvoljeno_odsustvo = models.BooleanField(default=False)
    nedozvoljeno_odsustvo = models.BooleanField(default=False)

    def __unicode__(self):
        return str(self.datum) + " - " + self.radnik.ime

    class Meta:
        verbose_name_plural = "Dani"


class Prihodi(models.Model):
    datum = models.DateField()
    vrsta = models.CharField(max_length=150)
    kolicina = models.FloatField(max_length=10, default=0.0)
    posao = models.ForeignKey(Poslovi, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.vrsta

    class Meta:
        verbose_name_plural = "Prihodi"


class Rashodi(models.Model):
    datum = models.DateField()
    vrsta = models.CharField(max_length=150)
    kolicina = models.FloatField(max_length=10, default=0.0)
    posao = models.ForeignKey(Poslovi, on_delete=models.CASCADE)
    vozilo = models.ForeignKey(Vozilo, null=True, blank=True )

    def __unicode__(self):
        return self.vrsta

    class Meta:
        verbose_name_plural = "Rashodi"


class Akontacije(models.Model):
    godina = models.IntegerField()
    mesec = models.IntegerField()
    kolicina = models.FloatField(default=0.0)
    radnik = models.ForeignKey(Radnik)

    def __unicode__(self):
        return self.radnik.ime

    class Meta:
        verbose_name_plural = "Akontacije"

class Komentar(models.Model):
    datum = models.DateField(null=True, blank=True)
    komentar = models.TextField()
    posao = models.ForeignKey(Poslovi, on_delete=models.CASCADE)

    def __unicode__(self):
        return str(self.posao)

    class Meta:
        verbose_name_plural = "Komentari"

projects/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Poslovi, Vozilo, Radnik, Prihodi, Rashodi, Dan, Zanimanja, Akontacije, Komentar

class DateInput(forms.DateInput):
    input_type = 'date'

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

class ZanimanjeForm(forms.ModelForm):
    class Meta:
        model = Zanimanja
        fields = ['zanimanje']

class PosloviForm(forms.ModelForm):
    pocetak_radova = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}),
        input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'))
    kraj_radova = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}),
        input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'),
        required=False)
    class Meta:
        model = Poslovi
        fields = ['ime', 'opis', 'dogovoreni_radni_sati', 'dogovoreno_po_kvadratu', 'pocetak_radova', 'kraj_radova']

class RadnikForm(forms.ModelForm):
    poceo_raditi = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}), input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'))
    ugovor_vazi_do = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}), input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'))
    class Meta:
        model = Radnik
        fields = ['ime', 'oib', 'poceo_raditi', 'ugovor_vazi_do', 'satnica', 'broj_telefona', 'broj_odela', 'broj_cipela', 'zaduzena_oprema', 'zanimanja', 'u_radnom_odnosu', 'komentar']
        widgets = {
            'zanimanja': forms.CheckboxSelectMultiple,
            'komentar': forms.Textarea
        }

class VoziloForm(forms.ModelForm):
    registracija_istice = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}), input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'))
    sledeci_servis = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}), input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'), required=False)
    class Meta:
        model = Vozilo
        fields = ['marka', 'predjeni_kilometri', 'registracija_istice', 'sledeci_servis', 'potrosnja_goriva', 'trenutno_duzi', 'opis']
        widgets = {
            'opis': forms.Textarea
        }

class RadnikForm__old(forms.ModelForm):
    class Meta:
        model = Radnik
        fields = ['ime', 'oib', 'poceo_raditi', 'ugovor_vazi_do', 'satnica', 'broj_telefona', 'broj_odela', 'broj_cipela', 'zaduzena_oprema', 'zanimanja']
        widgets = {
            'poceo_raditi': DateInput(),
            'ugovor_vazi_do': DateInput(),
            'zanimanja': forms.CheckboxSelectMultiple
        }

class PrihodiForm(forms.ModelForm):
    datum = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}),
        input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'))
    class Meta:
        model = Prihodi
        fields = ['datum', 'vrsta', 'kolicina']

class RashodiForm(forms.ModelForm):
    datum = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}),
        input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'))
    class Meta:
        model = Rashodi
        fields = ['datum', 'vrsta', 'kolicina', 'vozilo']


class KvadratForm(forms.Form):
    datum = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}),
        input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'))
    kolicina = forms.FloatField(label="kolicina")


class DatumForm(forms.Form):
    mesec = forms.IntegerField(max_value=12, min_value=1)
    godina = forms.IntegerField(label="godina")
    posao = forms.ModelChoiceField(queryset=Poslovi.objects.all(), required=False)

class Datum_finansForm(forms.Form):
    mesec = forms.IntegerField(max_value=12, min_value=1)
    godina = forms.IntegerField(label="godina")

class DanForm(forms.ModelForm):
    class Meta:
        model = Dan
        fields = ['radio_sati', 'ishrana', 'bolovanje', 'dozvoljeno_odsustvo', 'nedozvoljeno_odsustvo']

class AkontacijeForm(forms.ModelForm):
    class Meta:
        model = Akontacije
        fields = ['kolicina']

class KomentarForm(forms.ModelForm):
    datum = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}),
        input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'),
        required=False)
    class Meta:
        model = Komentar
        fields = ['datum', 'komentar']

projects/templates/projects/index.html
{% extends 'projects/base.html' %}
{% block title %} - Poslovi {% endblock %}
{% block content %}
{% load staticfiles %}

<div class="container">
    <h3>Poslovi</h3>
    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li style="color:red;" {% if message.tags == "success" %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}
    {% if poslovi_zavrseni_pre_vise_od_dve_godine %}
    <div class="row">
        <div class="col-sm-12" style="padding-bottom: 15px;">
            <ul class="list-group">
            {% for posao in poslovi_zavrseni_pre_vise_od_dve_godine %}
            <li class="list-group-item">{{ posao.ime }} - {{ posao.kraj_radova }}</li>
            {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}
    {% if poslovi %}
    <div class="row">
        <div class="col-sm-12" style="padding-bottom: 15px;">
            <br>
            <a href="{% url 'projects:project-add' %}">
                <button type="button" class="btn btn-primary">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Dodaj posao
                </button>
            </a>
        </div>
    </div>

    <div class="col-sm-12">
        <div class='container' id="table">
            <div class="table-div">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Ime</th>
                        <th>Opis</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for posao in poslovi %}
                    <tr>
                        <td><a href="{% url 'projects:posao' posao.id %}"><button type="button" class="btn btn-link">
                                    <span class="glyphicon glyphicon-wrench"></span>&nbsp; {{ posao.ime }}
                                </button></a></td>
                        <td>{{ posao.opis }}</td>
                        <td>
                            <a href="{% url 'projects:pdf_posao' posao.id %}">
                                <button type="button" class="btn btn-info">
                                    <span class="glyphicon glyphicon-pencil"></span>&nbsp; Napravi pdf izveštaj
                                </button>
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'projects:posao-delete' posao.id %}">
                                <button type="button" class="btn btn-danger" onclick="clicked(event)">
                                    <span class="glyphicon glyphicon-remove"></span>&nbsp; Obriši posao
                                </button>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    {% else %}
    <div class="row">
        <div class="col-sm-12" style="padding-bottom: 15px;">
            <br>
            <a href="{% url 'projects:project-add' %}">
                <button type="button" class="btn btn-primary">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Dodaj posao
                </button>
            </a>
        </div>
    </div>
    {% endif %}
</div>
<script>
function clicked(e)
{
    if(!confirm('Ako obrišete posao, obrisaće se svi prihodi, rashodi i dani koji su vezani za ovaj posao! Obrisati?'))e.preventDefault();
}
</script>
{% endblock %}





projects/templates/projects/ljudi.html
{% extends 'projects/base.html' %}
{% block title %} - Ljudi {% endblock %}
{% block content %}
{% load staticfiles %}

{% load widget_tweaks %}

<div class="container">
    <h3>Radnici</h3>
    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li {% if message.tags == "success" %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}
    <div class="row">
        <br>
        <a href="{% url 'projects:radnik-add' %}">
            <button type="button" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>&nbsp; Dodaj radnika
            </button>
        </a>
        <a href="{% url 'projects:zanimanje-add' %}">
            <button type="button" class="btn btn-warning">
                <span class="glyphicon glyphicon-plus"></span>&nbsp; Dodaj zanimanje
            </button>
        </a>
        <a href="{% url 'projects:biranje_meseca' %}" style="float: right">
            <button type="button" class="btn btn-warning">
                <span class="glyphicon glyphicon-calendar"></span>&nbsp; Mesecni izvod radnika
            </button>
        </a>
    </div>
    <hr style="height:1px;border:none;color:#333;background-color:#333;" />

    {% if radnici %}
    <div class="well">
        <form method="get">
            <h4 style="margin-top: 0">Filter</h4>
            <div class="row">
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.zanimanja.label_tag }}
                    {% render_field filter.form.zanimanja class="form-control" %}
                </div>
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.dostupan.label_tag }}
                    {% render_field filter.form.dostupan class="form-control" %}
                </div>
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.posao.label_tag }}
                    {% render_field filter.form.posao class="form-control" %}
                </div>
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.ugovor_vazi_do.label_tag }}
                    {% render_field filter.form.ugovor_vazi_do class="form-control" %}
                </div>
            </div>

                <button type="submit" class="btn btn-primary">
                    <span class="glyphicon glyphicon-search"></span> Potvrdi
                </button>
        </form>
    </div>
    <hr>
    <div class='container' id="table">
        <div class="table-div">
            <table class="table">
                <thead>
                <tr>
                    <th>Ime</th>
                    <th>Zanimanja</th>
                    <th>Dostupnost</th>
                    <th>Trenutno na poslu</th>
                    <th>Satnica</th>
                    <th>Ugovor važi do</th>
                    <th>Dana do isteka ugovora</th>
                </tr>
                </thead>
                <tbody>
                {% for radnik in filter.qs %}
                    {% if radnik.dostupan == True %}
                    <tr class="success">
                    {% else %}
                    <tr class="danger">
                    {% endif %}
                        <td><a href="{% url 'projects:radnik-detail' radnik.id %}">
                                <button type="button" class="btn btn-link">
                                    <span class="glyphicon glyphicon-user"></span>&nbsp; {{ radnik.ime }}
                                </button>
                            </a></td>
                        <td>* {% for j in radnik.zanimanja.all %}{{ j }} * {% endfor %}</td>
                        {% if radnik.dostupan == True %}
                        <td>Dostupan</td>
                        {% else %}
                        <td>Nedostupan</td>
                        {% endif %}
                        <td>{% if radnik.posao != None %}
                        <a href="{% url 'projects:posao' radnik.posao.id %}">{{ radnik.posao }}</a>
                        {% else %}
                        ---------------------
                        {% endif %}</td>
                        <td>{{ radnik.satnica }} kn</td>
                        <td {% if radnik.dana_do_isteka_ugovora < 15 %}style="color:red"{% endif %}>{{ radnik.ugovor_vazi_do }}</td>
                        <td {% if radnik.dana_do_isteka_ugovora < 15 %}style="color:red"{% endif %}>{{ radnik.dana_do_isteka_ugovora }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <hr style="height:1px;border:none;color:#333;background-color:#333;" />
    {% endif %}
    {% if radnici_otkaz %}
    <h4>Radnici kojima je prestao radni odnos</h4>
    <div class='container' id="table">
        <div class="table-div">
            <table class="table">
                <thead>
                <tr>
                    <th>Ime</th>
                    <th>oib</th>
                    <th>Zanimanja</th>
                </tr>
                </thead>
                <tbody>
                {% for radnik in radnici_otkaz %}
                    <tr class="danger">
                        <td><a href="{% url 'projects:radnik-update' radnik.id %}">
                                <button type="button" class="btn btn-link">
                                    <span class="glyphicon glyphicon-user"></span>&nbsp; {{ radnik.ime }}
                                </button>
                            </a></td>
                        <td>{{ radnik.oib }}</td>
                        <td>* {% for j in radnik.zanimanja.all %}{{ j }} * {% endfor %}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endif %}
</div>
{% endblock %}





projects/templates/projects/mesecni_izvod_finansije.html
{% extends 'projects/base.html' %}
{% block title %} - Finansije {% endblock %}
{% block content %}
{% load staticfiles %}

<div class="container">
    <h3>Finansije za {{ mesec }}.{{ godina }}</h3>
    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li style="color:red;" {% if message.tags == "success" %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}
    <div class='container'>
        <div class="col-sm-6">
            <a href="{% url 'projects:biranje_meseca_finansije' %}" style="float: right">
                <button type="button" class="btn btn-warning">
                    <span class="glyphicon glyphicon-calendar"></span>&nbsp; Izaberi drugi mesec
                </button>
            </a>
        </div>
        <div class="table-div">
            <table class="table">
                <thead>
                <tr>
                    <th>Posao</th>
                    <th>Prihodi</th>
                    <th>Rashodi</th>
                    <th>Dobit</th>
                </tr>
                </thead>
                <tbody>
                {% for posao in poslovi %}
                <tr>
                    <td><a href="{% url 'projects:posao' posao.id %}">
                            <button type="button" class="btn btn-link">
                                <span class="glyphicon glyphicon-wrench"></span>&nbsp; {{ posao.ime }}
                            </button>
                        </a>
                    </td>
                    {% for k, v in mesecni_prihodi.items %}
                    {% if k == posao.id %}
                    <td>{{ v }}</td>
                    {% endif %}
                    {% endfor %}
                    {% for k, v in mesecni_rashodi.items %}
                    {% if k == posao.id %}
                    <td>{{ v }}</td>
                    {% endif %}
                    {% endfor %}
                    {% for k, v in mesecno_dobit.items %}
                    {% if k == posao.id %}
                    <td>{{ v }}</td>
                    {% endif %}
                    {% endfor %}
                </tr>
                {% endfor %}
                <tr>
                    <td><strong>Ukupno:</strong></td>
                    <td><strong>{{ ukupni_prihodi }}</strong></td>
                    <td><strong>{{ ukupni_rashodi }}</strong></td>
                    <td><strong>{{ ukupna_dobit }}</strong></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

projects/templates/projects/vozilo_detalji.html
{% extends 'projects/base.html' %}
{% block title %} - Detalji - vozilo {% endblock %}
{% block projects_active %}active{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li style="color:red;" {% if message.tags == "success" %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    </div>
    <div class="row">
    <h1>{{ vozilo.marka }}</h1>

        <h4>Dana do isteka registracije: {{ preostalo_dana }}</h4>
        {% if vozilo.trenutno_duzi %}
        <h4>Trenutno duži: {{ vozilo.trenutno_duzi }}</h4>
        {% else %}
        <h4><font color="green"> Vozilo je dostupno!</font></h4>
        {% endif %}
        <br>
        <a href="{% url 'projects:vozilo-update' vozilo_id %}">
            <button type="button" class="btn btn-primary">
                <span class="glyphicon glyphicon-pencil"></span>&nbsp; Promeni detalje o vozilu
            </button>
        </a>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <h4>Predjeni kilometri:</h4>
            {% if vozilo.predjeni_kilometri %}
            <h3>{{ vozilo.predjeni_kilometri }}</h3>
            {% else %}
            <h3>Nije uneto</h3>
            {% endif %}
            <hr>
            <h4>Registracija ističe:</h4>
            <h3>{{ vozilo.registracija_istice }}</h3>
            <hr>
            <h4>Sledeći servis:</h4>
            <h3>{{ vozilo.sledeci_servis }}</h3>
            <hr>
            <h4>Potrošnja goriva:</h4>
            <h3>{{ vozilo.potrosnja_goriva }}</h3>
            <hr>
        </div>
    </div>
    {% if vozilo.opis %}
    <div class="col-xs-12">
        <h4>Opis:</h4>
            <h5>{{ vozilo.opis }}</h5>
    </div>
    {% endif %}
    <div class="col-xs-12">
        <h4>Rashodi:</h4>
         <table class="table">
             <thead>
             <tr>
                 <th>Količina</th>
                 <th>Vrsta</th>
                 <th>Posao</th>
                 <th>Datum</th>
             </tr>
             </thead>
             <tbody>
             {% for rashod in vozilo.rashodi_set.all %}
             <tr>
                 <td>{{ rashod.kolicina }}</td>
                 <td>{{ rashod.vrsta }}</td>
                 <td>{{ rashod.posao }}</td>
                 <td>{{ rashod.datum }}</td>
             </tr>
             {% endfor %}
             </tbody>
         </table>
    </div>
    <h3>Ukupni troškovi: {{ ukupni_troskovi }}</h3>
</div>
{% endblock %}